name: novabrowse

services:

  novabrowse:
    tty: true
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        NOTEBOOK: novabrowse_1.0.ipynb

    volumes:
      - ncbi_cache:/project/ncbi_cache

      - ../1_subject_sequences:/project/1_subject_sequences
      - ../2_subject_blastdb:/project/2_subject_blastdb
      - ../3_query_sequences:/project/3_query_sequences
      - ../4_blast_results:/project/4_blast_results

      - ../chromosome_data.json:/project/chromosome_data.json:ro
      - ../novabrowse_config.yaml:/project/novabrowse_config.yaml:ro

      - ./novabrowse_output:/project/novabrowse_output

    environment:
      ENTREZ_USE_CACHE: true
      ENTREZ_CACHE_SIZE_MB: 500
      ENTREZ_EMAIL_ENV: ""

volumes:
  ncbi_cache:
